//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public decimal EmployeeId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> ManagerId { get; set; }
        public int Age { get; set; }
        public decimal Salary { get; set; }
        public string Department { get; set; }
        public string ContactEmail { get; set; }
        public string Mobile { get; set; }
        public string Address { get; set; }
    }
}
